
import { mongoose, Schema } from 'models/mongodb/config'

// schema is just for default value, conversion..v..v
// must define here so we can update
const userSchema = Schema({
  username: { type: String },
  password: { type: String },
  name: { type: String },
  nameInApp: { type: String },
  avatarPath: { type: String },
  imagePathList: { type: [ String ] },
  dob: { type: Date },
  birthPlace: { type: String },
  createdDate: { type: Date },
  gender: { type: String },
  passport: { code: { type: String }, place: { type: String } },
  nationality: { type: String },
  religion: { type: String },
  nation: { type: String },
  address: { type: String },
  livingAddress: { type: String },
  language: { type: String },
  phone: { type: String },
  email: { type: String },
  highestEducationLevel: { type: String },
  latestCollege: { type: String },
  company: { type: String },
  position: { type: String },
  income: { type: String },
  family: { type: String },
  relation: { type: String },
  healthStatus: { type: String },
  note: { type: String },
  maritalStatus: { type: String },
  sonNumber: { type: Number },
  daughterNumber: { type: Number },
  height: { type: Number },
  weight: { type: Number },
  smokingStatus: { type: Number },
  drinkingStatus: { type: Number },
  workTimeStatus: { type: String },
  hobby: { type: String },
  favouriteQuotations: { type: String },
  sport: { type: Number },
  vehicle: { type: String },
  interestingRelationship: { type: [ String ] },
  otherInfo: { type: String },
  trait1: { type: Number },
  trait2: { type: Number },
  trait3: { type: Number },
  trait4: { type: Number },
  trait5: { type: Number },
  rating: { type: Number },
  active: { type: Number },
  deviceList: { type: [ Schema.Types.Mixed ] },
  latitude: { type: Number },
  longitude: { type: Number },
  lat: { type: Number },
  lon: { type: Number }, 
  logList: { type: [ Schema.Types.Mixed ] },
  seenNotiList: { type: [ String ] },
  favoriteList: { type: [ String ] } 
},{collection:'userList'})

export default mongoose.model('users', userSchema)
